import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
// import Image from 'next/image';
import Datatable from '../components/datatables/datatable';
// import styles from '../statics/css/Home.module.css';
import { mockDataTable, mockDataTable2 } from '../mock';

const Home: NextPage = () => {
  const [dataFetched, setDataFetched] = useState([]);

  const data = mockDataTable;
  const data2 = mockDataTable2;
  useEffect(() => {
    axios.get("https://jsonplaceholder.typicode.com/photos")
      .then(resp => {setDataFetched(resp.data)});
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossOrigin="anonymous"
        />
      </Head>

      <main></main>
      
      {dataFetched.length > 0 ? (
        <>
          <Datatable columns={{['id']: 'id', ['nome']: 'Nome', ['idade']: 'Idade', ['nacionalidade']: 'Nacionalidade'}} columnOrder={1} sortOrder={'desc'} entries={5} dataValues={data} mutipleDeleteReq={{url: "", method: "delete"}} showHeaderOptions showPagination isSelectable />
          {/* <Datatable columns={{}} columnOrder={1} sortOrder={'desc'} entries={5} dataValues={data} showHeaderOptions showPagination /> */}
          <Datatable columns={{['id']: 'id', ['idade']: 'Idade', ['nacionalidade']: 'Nacionalidade'}} dataValues={data2} />
          <Datatable columns={{['title']: 'title', ['url']: 'url', ['thumbnailUrl']: 'Tumbnail'}} dataValues={dataFetched} showHeaderOptions showPagination entries={10} columnOrder={1} sortOrder={'desc'} />
        </>
      ) : false}
    </div>
  );
};

export default Home;
